version: "3.9"
services:
  nginx:
    image: nginx:1.20.0-alpine
    ports:
      - "8001:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./breathe-india-frontend
    volumes:
      - frontend_dist:/app/nginx_volume
    env_file:
      - ./frontend.env
    depends_on:
      - backend
  backend:
    build: ./breathe-india-backend
    env_file:
      - ./backend.env
    depends_on:
      - postgres
  postgres:
    image: postgres:13.2-alpine
    env_file:
      - ./postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  frontend_dist: {}
