[package]
name = "breath-india-backend"
version = "0.1.0"
authors = ["Farseen <zah4n5dz@anonaddy.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
